# Generated by Django 3.2.5 on 2023-11-15 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('TournamentID', models.AutoField(primary_key=True, serialize=False)),
                ('TournamentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerID', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=100)),
                ('PlayerEmail', models.CharField(max_length=100)),
                ('PlayerPassword', models.CharField(max_length=100)),
                ('PlayerTournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pongapp.tournament')),
            ],
        ),
    ]
